add function calcIDataTransTech
e3modelling/mrprom pull request #51
Opened 2023-11-22 10:29 UTC by Fsioutas

add function calcIDataTransTech

2023-11-22 15:04 UTC, giannou requested changes
adding an updated version of the `sets.gms` file from OPEN-PROM might be needed

2023-11-23 08:45 UTC, Fsioutas commented on R/calcIDataTransTech.R
> +#' Use data to derive OPENPROM input parameter iDataTransTech
ok

2023-11-23 08:45 UTC, Fsioutas commented on R/calcIDataTransTech.R
> +  q$efficiency_value <- sub("_", ".", q$efficiency_value)
ok

2023-11-23 08:45 UTC, Fsioutas commented on R/calcIDataTransTech.R
> +  years <- c(2015, 2020, 2030, 2040, 2050)
ok

2023-11-23 08:45 UTC, Fsioutas commented on R/calcIDataTransTech.R
> +    index13 <- which(x$Var3 == 2015 & x$Var2 == map[i, 2] & x$Var1 == map[i, 1])
ok

2023-11-23 09:13 UTC, giannou approved these changes

2023-11-23 09:13 UTC, merged